baseURL = "https://marco.dev/"
languageCode = "en-us"
title = "Java and Angular in the Cloud"
theme = "m10c2"
[params]
author = "Marco Molteni"
description = " "
avatar = "marco.png"

[[params.social]]
  name = "github"
  url = "https://github.com/marco76"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/marcomolteni"
[markup.goldmark.renderer]
unsafe= true
